config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resource :users, only: [] do
    resources :products, only: [:new]
    get "/shop", to: "products#shop"
  end
  resources :products, except: [:new] do
    resources :carts, only: [:create]
  end
  resources :carts, only: %i[index destroy]
  resources :transactions, only: %i[index show create]
  resources :categories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model

  has_one_attached :photo
  belongs_to :category
  belongs_to :user
  has_many :transactions, dependent: :destroy
  has_many :carts
  after_save :default_image
  pg_search_scope :global_search,
                  against: %i[name description],
                  associated_against: {
                    category: [:name]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  validates_uniqueness_of :name, scope: :user
  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 10, maximum: 400 }
  validates :price, presence: true

  def default_image
    return if photo.presence

    photo.attach(io: open("http://res.cloudinary.com/dsgm7fnvb/image/upload/c_fill,h_300,w_400/#{category.photo.key}"),
                 filename: "#{name}.jpg")
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :photo
  has_many :products, dependent: :destroy
  has_many :transactions, dependent: :destroy
  has_one :cart, dependent: :destroy

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/,
                                                                message: 'Email invalid' }
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_category_array
  include Pundit

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  private

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name username email])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end

  def set_category_array
    # @category = Category.pluck(:name)
    @category = Category.all
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_cart, only: %i[destroy]

  def index
    @carts = policy_scope(Cart).where('user_id = :id', id: current_user.id)
  end

  def create
    cart = Cart.new(user_id: current_user.id, product_id: params[:product_id])
    authorize cart
    cart.save
    redirect_to products_path
  end

  def destroy
    authorize @cart
    @cart.destroy
    redirect_to carts_path
  end

  private

  def find_cart
    @cart = Cart.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_category, only: %i[edit update show destroy]

  def index
    @categories = policy_scope(Category).all
    authorize @categories
  end

  def show; end

  def new
    @category = Category.new
    authorize @category
  end

  def create
    @category = Category.new(category_params)
    authorize @category
    @category.save
    redirect_to category_path(@category)
  end

  def edit; end

  def update
    @category.update(category_params)
    redirect_to category_path(@category)
  end

  def destroy
    @category.destroy
    redirect_to categorys_path
  end

  private

  def category_params
    params.require(:category).permit(form_params)
  end

  def find_category
    @category = Category.find(params[:id])
    authorize @category
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[show edit destroy update]

  def index
    if params[:category].present?
      category = policy_scope(Category).where("name ILIKE :category", category: "%#{params[:category]}%").first
      @products = policy_scope(Product).where(category_id: category.id).order(created_at: :desc)
    elsif params[:query].present?
      products = policy_scope(Product).where("name ILIKE :query", query: "%#{params[:query]}%").order(created_at: :desc)
      @products = products
    else
      @products = policy_scope(Product).all
    end
  end

  def shop
    @products = policy_scope(Product).where(user_id: current_user.id).order(created_at: :desc)
    authorize @products
  end

  def show
  end

  def new
    @product = Product.new(user_id: current_user.id)
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    authorize @product
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to shop_users_path
  end

  private

  def set_product
    @product = policy_scope(Product).find(params[:id])
    authorize @product
  end

  def product_params
    params.require(:product).permit(:name, :description, :price, :availability, :category_id, :photo)
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @transactions = policy_scope(Transaction).where('user_id = :id', id: current_user.id)
  end

  def create
    carts = Cart.where('user_id = :id', id: current_user.id)
    carts.each do |cart|
      transaction = Transaction.new(user_id: current_user.id, product_id: cart.product.id)
      authorize transaction
      transaction.save!
      cart.destroy
    end
    redirect_to transactions_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/index.html.erb
<%= render 'shared/cart', carts: @carts %>

app/views/categories/index.html.erb
<% @categories.each do |category| %>
  <%= category.name %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCave</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('logo.png') %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'banner.jpg' %>);">
  <div class="container">
    <h1 id="home-title">My cave</h1>
    <p>Your personal cave straight to your door, sell, buy, drink !</p>
    <%= form_tag products_path, method: :get do %>
      <div class="d-flex">
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            id: "searchinput",
            placeholder: "Find a product"
          %>
        <%= submit_tag "Search", class: "btn", id: "searchbutton" %>
      <% end %>
    </div>
  </div>
</div>
<div class="container">
  <div class="cards">
    <%= link_to products_path(category: 'beer') do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'biere.jpg' %>);">
        Beers
      </div>
    <% end %>
    <%= link_to products_path(category: 'wine') do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'wine.jpg' %>);">
        Wine
      </div>
    <% end %>
    <%= link_to products_path(category: 'champagne') do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'champagne.jpg' %>)">
        Champagne
      </div>
    <% end %>
    <%= link_to products_path(category: 'liquors') do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'liquors.jpg' %>);">
        Liquors
      </div>
    <% end %>
    <%= link_to products_path do %>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= asset_path 'allproducts.jpg' %>)">
        All Products
      </div>
    <% end %>
  </div>
</div>

app/views/products/_form.html.erb
<div class="container size-container">
<%= simple_form_for product do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.association :category %>
  <%= f.input :price, as: :integer %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<div class="container size-container">
  <div class="all">
    <% @products.each do |product| %>
      <div class="card-product" data-category="<%= product.category_id %>" >
        <%= link_to product_path(product.id) do %>
          <div class="card-img-top">
            <%= cl_image_tag product.photo.key, class:"img-card", width: 300, height: 300 %>
          </div>
        <% end %>
        <div class="card-body">
          <%= link_to product_path(product.id) do %>
            <h5 class="card-title"><%= product.name %></h5>
          <% end %>
          <h6 class="card-username mb-2 text-muted"><%= product.user.username %></h6>
          <div class="card-text">
            <%= product.description.truncate(60, separator: /[\.\,: ]/, omission: ' ...') %>
          </div>
        </div>
        <div class="card-footer d-flex">
          <div class="card-product-pricing text-success">
            <h5 id="prix"><%= product.price %>€</h5>
          </div>
          <%= link_to product_carts_path(product.id), class:"btn btn-ghost-revert", method: :post do %>
            <i class="fas fa-shopping-cart"></i>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<%= render "form", product: @product %>

app/views/products/shop.html.erb
<div class="container size-container">
  <h1>My products</h1>
  <% @products.each do |product| %>
    <%= link_to product do %>
      <div class="card-list">
        <%= cl_image_tag product.photo.key %>
        <div class="card-list-infos">
          <h4 style="text-decoration: none"><%= product.name %></h4>
          <div class="d-flex">
          <h2><%= link_to "Modify", edit_product_path(product), class: "text-success"  %></h2>
          <h2><%= link_to "Delete", product, method: "delete", class: "text-danger", data: {confirm: "Are you sure?"}  %></h2>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
<div class="container">
  <%= link_to "New product", new_users_product_path, class: "btn btn-ghost-revert" %>
</div>
</div>

app/views/products/show.html.erb
<div class="container size-container">
<%= cl_image_tag @product.photo.key, height: 300, width: 400, crop: :fill %>
<h1>
<%= @product.name %>
</h1>

<h3> <%= @product.description %> </h3>
<h6> <%= @product.price %>€ </h6>

<h6>Vendeur : <%= @product.user.username %> </h6>
<%= link_to product_carts_path(@product.id), class:"btn btn-ghost-revert m-1", method: :post do %>
  Add this product to cart <i class="fas fa-shopping-cart"></i>
<% end %>
<%= link_to 'Back', :back, class: "btn btn-ghost-revert" %>
</div>

app/views/shared/_cart.html.erb
<div class="container size-container">
  <div class = "container-flex">
    <% @carts.each do |cart| %>
      <div class="cards-product-transaction m-3">
        <%= cl_image_tag cart.product.photo.key %>
        <div class="card-product-infos">
          <div>
            <h2><%= cart.product.name %></h2>
            <p><%= cart.product.description %></p>
          </div>
          <div>
          <h2><strong><%= cart.product.price %> €</strong></h2>
          <p><%= link_to "Delete", cart, method: "delete", class: "text-danger", data: {confirm: "Are you sure?"}  %></p>
          </div>
        </div>
      </div>
    <% end %>
    <% total = 0 %>
    <% carts.each do |item| %>
    <% total += item.product.price %>
    <% end %>
    <% unless carts.empty? %>
      <div>
        <h5>Total :<%= total %>€</h5>
      </div>
      <%= link_to  "VALID CART & PAY", transactions_path, method: :post, class: "btn btn-ghost-revert" %>
      <%= link_to 'Continue Shopping', :back, class: "btn btn-ghost-revert" %>
    <% end %>
</div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    My Cave is made with <i class="fas fa-heart"></i> by RaveTeam
  </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light <%= action_name == "home" ? "navbar-for-home" : "navbar-common" %>" >
  <a class="navbar-brand" href="/"><img src="<%= action_name == "home" ? ( asset_path 'logotransparent.png' ) : ( asset_path 'logotransparentblanc.png') %>" alt="logo">
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <% if action_name != 'home' %>
          <li class="nav-item d-flex active">
            <%= collection_select(:category, :filter, @category, :id, :name, {include_blank: 'All products'}) %>
            <%= form_tag products_path, method: :get do %>
              <div class="d-flex">
                <%= text_field_tag :query,
                    params[:query],
                    class: "form-control",
                    id: "searchinput",
                    placeholder: "Find a product"
                  %>
                <%= submit_tag "Search", class: "btn", id: "searchbutton" %>
              <% end %>
            </li>
          <%end%>
          <li class="nav-item d-flex active">
            <%= link_to "Home", "/", class: "nav-link" %>
          </li>
          <li class="nav-item d-flex active">
            <%= link_to "/carts", class: "nav-link" do %>
              <i class="fas fa-shopping-cart"></i>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://res.cloudinary.com/dykscnyvu/image/upload/v1605781227/B9724176933Z.1_20200802161018_000_GHQGE7FJ8.1-0_dfy3jr.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "My products", shop_users_path, class: "dropdown-item" %>
              <%= link_to "Create a product", new_users_product_path, class: "dropdown-item" %>
              <%= link_to "My transactions", transactions_path, class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <button type="button" class="btn btn-ghost" data-toggle="modal" data-target="#registerModal">
              Register
            </button>
            <button type="button" class="btn btn-ghost" data-toggle="modal" data-target="#loginModal">
              Login
            </button>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="modal fade" id="registerModal" tabindex="-1" aria-labelledby="registerModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="background-color: #3D0016; color: white">
          <h5 class="modal-title" id="registerModalLabel">Registration</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: white">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for(User.new, as: :user, url: registration_path(:user)) do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :email,
                        required: true,
                        autofocus: true,
                        input_html: { autocomplete: "email" }%>
              <%= f.input :username,
                        required: true,
                        input_html: { autocomplete: "username" }%>
              <%= f.input :first_name,
                        required: true,
                        input_html: { autocomplete: "first_name" }%>
              <%= f.input :last_name,
                        required: true,
                        input_html: { autocomplete: "last_name" }%>
              <%= f.input :password,
                        required: true,
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        input_html: { autocomplete: "new-password" } %>
              <%= f.input :password_confirmation,
                        required: true,
                        input_html: { autocomplete: "new-password" } %>
            </div>
          </div>
          <div class="modal-footer" style="background-color: #3D0016; color: white">
            <div class="form-actions">
              <button type="button" class="btn btn-ghost-revert" data-dismiss="modal">Close</button>
              <%= f.button :submit, "Sign up", class: "btn btn-ghost" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="background-color: #3D0016; color: white">
          <h5 class="modal-title" id="loginModalLabel">Registration</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" style="color: white">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= simple_form_for(User.new, as: :user, url: session_path(:user)) do |f| %>
            <div class="form-inputs">
              <%= f.input :email,
                        required: false,
                        autofocus: true,
                        input_html: { autocomplete: "email" } %>
              <%= f.input :password,
                        required: false,
                        input_html: { autocomplete: "current-password" } %>
              <%= f.input :remember_me, as: :boolean %>
            </div>
          </div>
          <div class="modal-footer" style="background-color: #3D0016; color: white">
            <div class="form-actions">
              <button type="button" class="btn btn-ghost-revert" data-dismiss="modal">Close</button>
              <%= f.button :submit, "Login", class: "btn btn-ghost" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/transactions/index.html.erb
<div class="container size-container">
  <div class = "container">
    <% @transactions.each do |transaction| %>
      <div class="cards-product-transaction m-3">
        <%= cl_image_tag transaction.product.photo.key %>
        <div class="card-product-infos">
          <div>
            <h2><%= transaction.product.name %></h2>
            <p><%= transaction.product.description.truncate(40, separator: /[\.\,: ]/, omission: ' ...') %></p>
          </div>
          <p>date d'achat: <%= transaction.created_at.strftime('%d-%m-%Y') %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>